# Generated by Django 4.1.3 on 2022-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="work_experience",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Опыт работы в семьях",
            ),
        ),
    ]
