# Generated by Django 4.1.3 on 2022-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_applicant_doc_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="family",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
    ]
