# Generated by Django 4.1.3 on 2023-01-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_applicant_questionnaire_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="applicants"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="doc_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Примечания"),
        ),
    ]
